### ISSUE TITLE
Property 'mysql' does not exist on type 'X'

### ISSUE THREAD

**Issue by lazuee** [mateonunez/fastify-at-mysql#36]
[Screenshot 2023-10-22 at 15.29.53.webm](https://github.com/mateonunez/fastify-at-mysql/assets/91590512/50d510d4-d262-49e0-9b09-8cbf81eb956a)

```
Property 'mysql' does not exist on type 'FastifyInstance<Server<typeof IncomingMessage, typeof ServerResponse>, IncomingMessage, ServerResponse<IncomingMessage>, FastifyBaseLogger, FastifyTypeProviderDefault> & PromiseLike<...>'.ts(2339)
```

**Comment by mateonunez** [comment]
Hey @lazuee, thanks for reporting this.

Would you send a PR to fix types?

**Comment by mateonunez** [comment]
The `v0.3.0` fixes this error. Please update your version. Thank you.

**Comment by lazuee** [comment]
thanks for the update :)
